language: ruby
before_script:
- RAILS_ENV=test rake setup:vcr_directory
env:
  secure: CjXNdREwWb7OD6RFBI5ulQ5K8GugP8xyP8QxgArPLVh7+P7Hq7IrYiwQEYIzkiIwxkzUZjjklyVJq5ofC4wRC3m5tMAGbbrQ10YeUJPPrCgKHUr0zfVQcF1I7zev2ae5t7rWRKoYRAOvwRj0Ouf024rsZshlzQRZg/3PxAtpWQc=
